### ISSUE TITLE
Analysis script

### ISSUE THREAD

**Issue by suuuuperNOVA** [UBC-MDS/tech_salary_predictor_canada_us#29]
A couple of things need to do:
1. the inputs are hard coded,
2. when saving the model, you saved an empty model. I need a trained model like coefficients of the features.
    when I load the model, make sure I don't need to train them.
3. Also save R^2 value

**Comment by khalidcawl** [comment]
Hi @suuuuperNOVA . Thanks for the comment. 
- The inputs at the top are the default values. Once you pass something in the command line, it should use those inputs
- The object I saved is a Pipeline object, so you will need to access the named steps and extract the estimator. However, I updated this part just now. I will share the code on how to get the model object.
- Good idea. I will try to save a table and a figure for hyper-parameter tuning.
