### ISSUE TITLE
Enquiring about final report 

### ISSUE THREAD

**Issue by nd265** [UBC-MDS/tech_salary_predictor_canada_us#50]
Hi team, 

I just wanted to confirm if this the link of your final report? https://github.com/UBC-MDS/tech_salary_predictor_canada_us/blob/main/docs/report.ipynb ? @khalidcawl @suuuuperNOVA @Sanchit120496 @hjw0703

**Comment by khalidcawl** [comment]
Hi @nd265 the milestone release is here: https://github.com/UBC-MDS/tech_salary_predictor_canada_us/tree/0.1.0
The report should be https://github.com/UBC-MDS/tech_salary_predictor_canada_us/blob/0.1.0/doc/tech_salary_predictor_report/_build/html/index.html

@suuuuperNOVA is that correct?

**Comment by suuuuperNOVA** [comment]
yes

**Comment by nd265** [comment]
Thanks guys!
