### ISSUE TITLE
Attach issue links to the feedback

### ISSUE THREAD

**Issue by khalidcawl** [UBC-MDS/tech_salary_predictor_canada_us#62]

**Comment by suuuuperNOVA** [comment]
1. Reply to TA's review on Milestone 1: https://github.com/UBC-MDS/tech_salary_predictor_canada_us/issues/39#issuecomment-991140454 <br>
2. Reply to TA's review on Milestone 2: https://github.com/UBC-MDS/tech_salary_predictor_canada_us/issues/64#issuecomment-990906501 <br>
3. Reply to @khbunyan peer review: https://github.com/UBC-MDS/data-analysis-review-2021/issues/17#issuecomment-991146274 <br>
4. Reply to @nd265 peer review: https://github.com/UBC-MDS/data-analysis-review-2021/issues/17#issuecomment-991151146 <br>
